"""Curated galleries of icons, colour palettes, and font samples.

These are exposed to the GUI/TUI editor so users can pick from a rich
catalog of pre-built choices instead of typing Unicode codepoints or hex
codes by hand. Every gallery is a plain Python data structure so it can
also be consumed by tests, the TUI, and external tooling.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# Icon gallery
# ---------------------------------------------------------------------------

@dataclass
class IconEntry:
    glyph: str
    name: str
    keywords: Tuple[str, ...] = field(default_factory=tuple)


# Curated, themed catalogues of pure-Unicode glyphs (emoji + symbols) that
# render in any modern terminal/Tk widget without external font files.
ICON_GALLERY: Dict[str, List[IconEntry]] = {
    "Finance & Markets": [
        IconEntry("📈", "trend up", ("growth", "bull", "rise")),
        IconEntry("📉", "trend down", ("loss", "bear", "fall")),
        IconEntry("📊", "bar chart", ("dashboard", "stats")),
        IconEntry("💹", "yen chart up", ("forex", "fx", "asia")),
        IconEntry("💰", "money bag", ("cash", "savings")),
        IconEntry("💵", "dollar bill", ("usd", "money")),
        IconEntry("💴", "yen bill", ("jpy", "money")),
        IconEntry("💶", "euro bill", ("eur", "money")),
        IconEntry("💷", "pound bill", ("gbp", "money")),
        IconEntry("🪙", "coin", ("crypto", "metal")),
        IconEntry("💳", "credit card", ("payment", "spend")),
        IconEntry("🏦", "bank", ("vault", "deposit")),
        IconEntry("🏛", "classical building", ("treasury", "central bank")),
        IconEntry("📅", "calendar", ("date", "schedule", "earnings")),
        IconEntry("⏰", "alarm", ("alert", "deadline")),
        IconEntry("⏳", "hourglass flow", ("pending", "wait")),
        IconEntry("🔒", "lock", ("escrow", "secure")),
        IconEntry("🔓", "unlock", ("released", "open")),
        IconEntry("📦", "package", ("etf basket", "holding")),
        IconEntry("🧾", "receipt", ("invoice", "tax")),
        IconEntry("💎", "diamond", ("hold", "long-term")),
        IconEntry("🐂", "bull", ("bull market",)),
        IconEntry("🐻", "bear", ("bear market",)),
    ],
    "Status & Verdict": [
        IconEntry("✓", "check", ("ok", "pass", "success")),
        IconEntry("✘", "cross", ("fail", "error", "no")),
        IconEntry("⚠", "warning", ("caution", "yellow")),
        IconEntry("ⓘ", "info circle", ("note",)),
        IconEntry("❓", "question", ("unknown",)),
        IconEntry("❗", "exclamation", ("alert",)),
        IconEntry("🚫", "prohibited", ("avoid", "blocked")),
        IconEntry("⛔", "no entry", ("stop",)),
        IconEntry("✅", "green check", ("done",)),
        IconEntry("❌", "red x", ("rejected",)),
        IconEntry("🟢", "green dot", ("buy", "positive")),
        IconEntry("🟡", "yellow dot", ("hold", "neutral")),
        IconEntry("🔴", "red dot", ("sell", "risk")),
        IconEntry("🔵", "blue dot", ("info", "neutral")),
        IconEntry("⚪", "white dot", ("muted",)),
        IconEntry("⚫", "black dot", ("muted",)),
        IconEntry("🟣", "purple dot", ("agent",)),
        IconEntry("🟠", "orange dot", ("warning", "tier-micro")),
        IconEntry("⭐", "star", ("favorite", "default")),
        IconEntry("🏆", "trophy", ("winner", "top pick")),
        IconEntry("🥇", "gold medal", ("first",)),
        IconEntry("🥈", "silver medal", ("second",)),
        IconEntry("🥉", "bronze medal", ("third",)),
    ],
    "Navigation & Actions": [
        IconEntry("📥", "inbox", ("load", "import")),
        IconEntry("📤", "outbox", ("export",)),
        IconEntry("💾", "floppy", ("save",)),
        IconEntry("📂", "folder open", ("load", "browse")),
        IconEntry("📁", "folder", ("directory",)),
        IconEntry("🔍", "magnifier", ("search", "find")),
        IconEntry("🔎", "magnifier right", ("search",)),
        IconEntry("🗑", "trash", ("delete", "remove")),
        IconEntry("✏", "pencil", ("edit",)),
        IconEntry("📝", "memo", ("notes",)),
        IconEntry("🖨", "printer", ("print",)),
        IconEntry("🔄", "refresh cycle", ("reload",)),
        IconEntry("🔃", "refresh down-up", ("sync",)),
        IconEntry("↩", "return", ("back",)),
        IconEntry("↪", "forward", ("redo",)),
        IconEntry("⏮", "skip back", ("first",)),
        IconEntry("⏭", "skip forward", ("last",)),
        IconEntry("⏯", "play/pause", ("toggle",)),
        IconEntry("⏸", "pause", ("hold",)),
        IconEntry("▶", "play", ("run", "go")),
        IconEntry("⏹", "stop", ("halt",)),
        IconEntry("➕", "plus", ("add",)),
        IconEntry("➖", "minus", ("remove",)),
        IconEntry("✕", "small x", ("close",)),
        IconEntry("⚙", "gear", ("settings",)),
        IconEntry("🔧", "wrench", ("config",)),
        IconEntry("🔨", "hammer", ("build",)),
    ],
    "Communication & Docs": [
        IconEntry("📧", "email", ("mail", "contact")),
        IconEntry("📨", "incoming envelope", ("inbox",)),
        IconEntry("📬", "mailbox", ("inbox",)),
        IconEntry("📞", "phone", ("call",)),
        IconEntry("📡", "satellite", ("feed",)),
        IconEntry("📰", "newspaper", ("news", "article")),
        IconEntry("📜", "scroll", ("doc", "license")),
        IconEntry("📄", "document", ("file", "page")),
        IconEntry("📃", "page curl", ("doc",)),
        IconEntry("📑", "tabs", ("bookmarks",)),
        IconEntry("🔖", "bookmark", ("favorite",)),
        IconEntry("📚", "books", ("library",)),
        IconEntry("📖", "open book", ("reading",)),
        IconEntry("📘", "blue book", ("manual",)),
        IconEntry("📙", "orange book", ("guide",)),
        IconEntry("📕", "red book", ("alert doc",)),
        IconEntry("📗", "green book", ("approved doc",)),
    ],
    "Data & Analytics": [
        IconEntry("🧮", "abacus", ("calculate",)),
        IconEntry("📐", "ruler", ("measure",)),
        IconEntry("📏", "straight ruler", ("scale",)),
        IconEntry("🧪", "test tube", ("experiment", "analysis")),
        IconEntry("🔬", "microscope", ("research",)),
        IconEntry("🧬", "dna", ("genome", "deep")),
        IconEntry("🗂", "card index", ("archive",)),
        IconEntry("🗃", "file box", ("archive",)),
        IconEntry("🗄", "filing cabinet", ("storage",)),
        IconEntry("📋", "clipboard", ("checklist",)),
        IconEntry("🖥", "desktop", ("workstation",)),
        IconEntry("💻", "laptop", ("dev",)),
        IconEntry("⌨", "keyboard", ("input",)),
        IconEntry("🖱", "mouse", ("input",)),
        IconEntry("🤖", "robot", ("agent", "ai")),
        IconEntry("🧠", "brain", ("ai", "thought")),
        IconEntry("🛰", "satellite", ("signal", "feed")),
    ],
    "World & Languages": [
        IconEntry("🌐", "globe meridians", ("world", "international")),
        IconEntry("🌍", "globe europe-africa", ("emea",)),
        IconEntry("🌎", "globe americas", ("us", "latam")),
        IconEntry("🌏", "globe asia-australia", ("apac",)),
        IconEntry("🗺", "world map", ("geo",)),
        IconEntry("🇺🇸", "flag US", ("us", "english")),
        IconEntry("🇪🇸", "flag ES", ("spain", "spanish")),
        IconEntry("🇮🇹", "flag IT", ("italy", "italian")),
        IconEntry("🇩🇪", "flag DE", ("germany", "german")),
        IconEntry("🇫🇷", "flag FR", ("france", "french")),
        IconEntry("🇮🇷", "flag IR", ("iran", "farsi")),
        IconEntry("🇬🇧", "flag GB", ("uk",)),
        IconEntry("🇯🇵", "flag JP", ("japan",)),
        IconEntry("🇨🇳", "flag CN", ("china",)),
        IconEntry("🇧🇷", "flag BR", ("brazil",)),
    ],
    "Sectors & Industry": [
        IconEntry("⚡", "bolt", ("energy", "electric")),
        IconEntry("🔋", "battery", ("energy storage",)),
        IconEntry("☢", "radioactive", ("nuclear",)),
        IconEntry("🛢", "oil drum", ("oil", "energy")),
        IconEntry("🌱", "seedling", ("esg", "growth")),
        IconEntry("🌿", "herb", ("esg", "green")),
        IconEntry("🏭", "factory", ("industrials",)),
        IconEntry("🏗", "construction", ("infra",)),
        IconEntry("🏠", "house", ("real estate",)),
        IconEntry("🏢", "office", ("reit", "corporate")),
        IconEntry("🏬", "department store", ("retail", "consumer")),
        IconEntry("🚗", "car", ("autos",)),
        IconEntry("✈", "plane", ("airlines", "travel")),
        IconEntry("🚢", "ship", ("shipping",)),
        IconEntry("🛒", "cart", ("retail",)),
        IconEntry("🍎", "apple", ("consumer", "food")),
        IconEntry("☕", "coffee", ("consumer",)),
        IconEntry("🩺", "stethoscope", ("healthcare",)),
        IconEntry("💊", "pill", ("pharma",)),
        IconEntry("🧬", "dna", ("biotech",)),
        IconEntry("📱", "phone", ("tech",)),
        IconEntry("🎮", "controller", ("gaming",)),
        IconEntry("🎬", "clapper", ("media",)),
    ],
    "Symbols & Misc": [
        IconEntry("♥", "heart", ("favorite",)),
        IconEntry("♠", "spade", ("card",)),
        IconEntry("♦", "diamond suit", ("card",)),
        IconEntry("♣", "club", ("card",)),
        IconEntry("♻", "recycle", ("loop", "esg")),
        IconEntry("⚖", "balance", ("legal", "compare")),
        IconEntry("⚓", "anchor", ("stable",)),
        IconEntry("⌘", "command", ("shortcut",)),
        IconEntry("⏱", "stopwatch", ("benchmark",)),
        IconEntry("⏲", "timer", ("countdown",)),
        IconEntry("☀", "sun", ("light",)),
        IconEntry("☁", "cloud", ("backup",)),
        IconEntry("☂", "umbrella", ("hedge",)),
        IconEntry("☔", "umbrella with rain", ("protection",)),
        IconEntry("☘", "shamrock", ("luck",)),
        IconEntry("☄", "comet", ("burst",)),
        IconEntry("⚛", "atom", ("science",)),
        IconEntry("∞", "infinity", ("forever",)),
        IconEntry("∑", "sigma", ("sum",)),
        IconEntry("π", "pi", ("constant",)),
        IconEntry("∫", "integral", ("calculus",)),
        IconEntry("≈", "almost equal", ("approx",)),
        IconEntry("≠", "not equal", ("diff",)),
        IconEntry("≤", "less or equal", ("bound",)),
        IconEntry("≥", "greater or equal", ("bound",)),
    ],
    "Arrows": [
        IconEntry("←", "left arrow", ("back", "previous")),
        IconEntry("→", "right arrow", ("forward", "next")),
        IconEntry("↑", "up arrow", ("rise", "north")),
        IconEntry("↓", "down arrow", ("fall", "south")),
        IconEntry("↔", "left-right arrow", ("range", "horizontal")),
        IconEntry("↕", "up-down arrow", ("vertical",)),
        IconEntry("↖", "northwest arrow", ()),
        IconEntry("↗", "northeast arrow", ("growth", "up-right")),
        IconEntry("↘", "southeast arrow", ("decline",)),
        IconEntry("↙", "southwest arrow", ()),
        IconEntry("⇐", "double left arrow", ("step back",)),
        IconEntry("⇒", "double right arrow", ("implies",)),
        IconEntry("⇑", "double up arrow", ("strong rise",)),
        IconEntry("⇓", "double down arrow", ("strong fall",)),
        IconEntry("⇔", "double left-right", ("biconditional",)),
        IconEntry("⇕", "double up-down", ("toggle",)),
        IconEntry("➡", "rightwards black arrow", ("emphasis",)),
        IconEntry("⬅", "leftwards black arrow", ("back",)),
        IconEntry("⬆", "upwards black arrow", ()),
        IconEntry("⬇", "downwards black arrow", ()),
        IconEntry("➜", "rounded right arrow", ("call to action",)),
        IconEntry("➤", "black rightwards arrowhead", ("next",)),
        IconEntry("➔", "heavy rightwards arrow", ()),
        IconEntry("➞", "long rightwards arrow", ("flow",)),
        IconEntry("➢", "thick three-quarters arrow", ()),
        IconEntry("➣", "rightwards triangle-headed arrow", ()),
        IconEntry("⤴", "arrow up-right curve", ("recovery",)),
        IconEntry("⤵", "arrow down-right curve", ("dip",)),
        IconEntry("↩", "leftwards return", ("undo",)),
        IconEntry("↪", "rightwards return", ("redo",)),
        IconEntry("⟶", "long right arrow", ("flow",)),
        IconEntry("⟵", "long left arrow", ("flow",)),
        IconEntry("⤶", "down-left return", ()),
        IconEntry("⤷", "down-right return", ()),
        IconEntry("⇄", "left-right pair", ("swap",)),
        IconEntry("⇅", "up-down pair", ("toggle",)),
        IconEntry("⇆", "left-right alt pair", ("exchange",)),
        IconEntry("⇇", "leftwards paired", ("merge left",)),
        IconEntry("⇉", "rightwards paired", ("merge right",)),
        IconEntry("↻", "clockwise", ("rotate", "redo")),
        IconEntry("↺", "counterclockwise", ("rotate", "undo")),
    ],
    "Geometric Shapes": [
        IconEntry("●", "filled circle", ("dot",)),
        IconEntry("○", "circle", ("ring",)),
        IconEntry("◉", "fisheye", ("target",)),
        IconEntry("◎", "bullseye", ("target",)),
        IconEntry("◐", "circle left half", ("phase",)),
        IconEntry("◑", "circle right half", ("phase",)),
        IconEntry("◒", "circle bottom half", ("phase",)),
        IconEntry("◓", "circle top half", ("phase",)),
        IconEntry("◔", "quarter circle", ("25 percent",)),
        IconEntry("◕", "three-quarters circle", ("75 percent",)),
        IconEntry("◖", "left semicircle", ()),
        IconEntry("◗", "right semicircle", ()),
        IconEntry("■", "filled square", ("block",)),
        IconEntry("□", "square", ("box",)),
        IconEntry("▣", "square containing square", ("frame",)),
        IconEntry("▤", "square horizontal fill", ()),
        IconEntry("▥", "square vertical fill", ()),
        IconEntry("▦", "square orthogonal fill", ()),
        IconEntry("▧", "square upper left fill", ()),
        IconEntry("▨", "square upper right fill", ()),
        IconEntry("▩", "square diagonal fill", ()),
        IconEntry("▪", "small filled square", ("dot",)),
        IconEntry("▫", "small square", ()),
        IconEntry("▲", "filled triangle up", ("rise", "growth")),
        IconEntry("△", "triangle up", ()),
        IconEntry("▼", "filled triangle down", ("decline",)),
        IconEntry("▽", "triangle down", ()),
        IconEntry("◀", "filled triangle left", ("back",)),
        IconEntry("▶", "filled triangle right", ("play", "next")),
        IconEntry("◁", "triangle left", ()),
        IconEntry("▷", "triangle right", ()),
        IconEntry("◆", "filled diamond", ("decoration", "lynx")),
        IconEntry("◇", "diamond", ()),
        IconEntry("◈", "diamond with diamond", ("ornament",)),
        IconEntry("◊", "lozenge", ()),
        IconEntry("◢", "lower right triangle", ()),
        IconEntry("◣", "lower left triangle", ()),
        IconEntry("◤", "upper left triangle", ()),
        IconEntry("◥", "upper right triangle", ()),
        IconEntry("⬛", "black large square", ()),
        IconEntry("⬜", "white large square", ()),
        IconEntry("⬟", "black pentagon", ()),
        IconEntry("⬢", "black hexagon", ()),
        IconEntry("⬡", "white hexagon", ()),
        IconEntry("⭕", "hollow red circle", ("zero", "blocker")),
        IconEntry("✦", "black four-pointed star", ()),
        IconEntry("✧", "white four-pointed star", ()),
    ],
    "Stars & Sparkles": [
        IconEntry("★", "filled star", ("rating",)),
        IconEntry("☆", "star", ("rating",)),
        IconEntry("✩", "lightweight star", ()),
        IconEntry("✪", "circled star", ("award",)),
        IconEntry("✫", "open centre black star", ()),
        IconEntry("✬", "black centre white star", ()),
        IconEntry("✭", "outlined black star", ()),
        IconEntry("✮", "heavy outlined star", ()),
        IconEntry("✯", "pinwheel star", ()),
        IconEntry("✰", "shadowed white star", ()),
        IconEntry("✱", "heavy asterisk", ()),
        IconEntry("✲", "open centre asterisk", ()),
        IconEntry("✳", "eight-spoked asterisk", ()),
        IconEntry("✴", "eight-pointed black star", ()),
        IconEntry("✵", "eight-pointed pinwheel", ()),
        IconEntry("✶", "six-pointed black star", ()),
        IconEntry("✷", "six-pointed asterisk", ()),
        IconEntry("✸", "heavy six-pointed star", ()),
        IconEntry("✹", "twelve-pointed black star", ()),
        IconEntry("✺", "sixteen-pointed asterisk", ()),
        IconEntry("✻", "teardrop-spoked asterisk", ()),
        IconEntry("✼", "open centre teardrop asterisk", ()),
        IconEntry("✽", "heavy teardrop-spoked asterisk", ()),
        IconEntry("✾", "six-petalled black-white florette", ()),
        IconEntry("✿", "black florette", ()),
        IconEntry("❀", "white florette", ()),
        IconEntry("❁", "eight-petalled outlined black florette", ()),
        IconEntry("❂", "circled open centre eight-pointed star", ()),
        IconEntry("❃", "heavy teardrop-spoked pinwheel asterisk", ()),
        IconEntry("❄", "snowflake", ("winter",)),
        IconEntry("❅", "tight trifoliate snowflake", ()),
        IconEntry("❆", "heavy chevron snowflake", ()),
        IconEntry("❇", "sparkle", ()),
        IconEntry("❈", "heavy sparkle", ()),
        IconEntry("❉", "balloon-spoked asterisk", ()),
        IconEntry("❊", "eight-teardrop-spoked propeller", ()),
        IconEntry("❋", "heavy eight-teardrop-spoked propeller", ()),
        IconEntry("✨", "sparkles", ("highlight",)),
        IconEntry("⚝", "outlined white star", ()),
        IconEntry("🌟", "glowing star", ("featured",)),
        IconEntry("🌠", "shooting star", ()),
    ],
    "Math & Logic": [
        IconEntry("±", "plus-minus", ("uncertainty",)),
        IconEntry("×", "multiplication", ("times",)),
        IconEntry("÷", "division", ()),
        IconEntry("√", "square root", ()),
        IconEntry("∛", "cube root", ()),
        IconEntry("∜", "fourth root", ()),
        IconEntry("∂", "partial differential", ()),
        IconEntry("∇", "nabla", ("gradient",)),
        IconEntry("∈", "element of", ("set",)),
        IconEntry("∉", "not element of", ("set",)),
        IconEntry("∋", "contains as member", ()),
        IconEntry("⊂", "subset of", ()),
        IconEntry("⊃", "superset of", ()),
        IconEntry("⊆", "subset or equal", ()),
        IconEntry("⊇", "superset or equal", ()),
        IconEntry("∪", "union", ()),
        IconEntry("∩", "intersection", ()),
        IconEntry("∅", "empty set", ()),
        IconEntry("∀", "for all", ()),
        IconEntry("∃", "there exists", ()),
        IconEntry("¬", "not", ("logical",)),
        IconEntry("∧", "logical and", ()),
        IconEntry("∨", "logical or", ()),
        IconEntry("⊕", "circled plus", ("xor",)),
        IconEntry("⊗", "circled times", ()),
        IconEntry("⊖", "circled minus", ()),
        IconEntry("⊘", "circled division", ()),
        IconEntry("⊥", "perpendicular", ()),
        IconEntry("∥", "parallel", ()),
        IconEntry("∝", "proportional", ()),
        IconEntry("∠", "angle", ()),
        IconEntry("⌀", "diameter sign", ()),
        IconEntry("℅", "care of", ()),
        IconEntry("№", "numero", ("number",)),
        IconEntry("℗", "sound recording copyright", ()),
        IconEntry("™", "trademark", ()),
        IconEntry("®", "registered", ()),
        IconEntry("©", "copyright", ()),
        IconEntry("℧", "mho", ("conductance",)),
        IconEntry("∮", "contour integral", ()),
        IconEntry("∝", "proportional to", ()),
        IconEntry("∼", "tilde operator", ("similar",)),
    ],
    "Currency Symbols": [
        IconEntry("$", "dollar", ("usd",)),
        IconEntry("€", "euro", ("eur",)),
        IconEntry("£", "pound", ("gbp",)),
        IconEntry("¥", "yen", ("jpy", "cny")),
        IconEntry("¢", "cent", ()),
        IconEntry("₿", "bitcoin", ("btc", "crypto")),
        IconEntry("₩", "won", ("krw",)),
        IconEntry("₪", "shekel", ("ils",)),
        IconEntry("₣", "french franc", ()),
        IconEntry("₤", "lira", ()),
        IconEntry("₧", "peseta", ()),
        IconEntry("₨", "rupee", ("inr", "pkr")),
        IconEntry("₫", "dong", ("vnd",)),
        IconEntry("₭", "kip", ("lak",)),
        IconEntry("₮", "tugrik", ("mnt",)),
        IconEntry("₱", "peso", ("php",)),
        IconEntry("₲", "guarani", ("pyg",)),
        IconEntry("₳", "austral", ()),
        IconEntry("₴", "hryvnia", ("uah",)),
        IconEntry("₵", "cedi", ("ghs",)),
        IconEntry("₸", "tenge", ("kzt",)),
        IconEntry("₹", "indian rupee", ("inr",)),
        IconEntry("₺", "lira sign", ("try",)),
        IconEntry("₼", "manat", ("azn",)),
        IconEntry("₽", "ruble", ("rub",)),
        IconEntry("Ƀ", "old bitcoin", ("btc",)),
        IconEntry("Ł", "litecoin / polish złoty", ("ltc", "pln")),
        IconEntry("Ξ", "ether", ("eth",)),
        IconEntry("฿", "thai baht", ("thb",)),
        IconEntry("Ð", "dogecoin", ("doge",)),
        IconEntry("Ʀ", "ripple", ("xrp",)),
        IconEntry("kr", "krona", ("sek", "nok", "dkk")),
        IconEntry("zł", "złoty", ("pln",)),
        IconEntry("Kč", "czech koruna", ("czk",)),
        IconEntry("Ft", "forint", ("huf",)),
        IconEntry("R$", "real", ("brl",)),
    ],
    "Box Drawing & Lines": [
        IconEntry("─", "light horizontal", ("divider",)),
        IconEntry("━", "heavy horizontal", ("divider",)),
        IconEntry("│", "light vertical", ()),
        IconEntry("┃", "heavy vertical", ()),
        IconEntry("┌", "light down-right corner", ()),
        IconEntry("┐", "light down-left corner", ()),
        IconEntry("└", "light up-right corner", ()),
        IconEntry("┘", "light up-left corner", ()),
        IconEntry("├", "light vertical-right", ()),
        IconEntry("┤", "light vertical-left", ()),
        IconEntry("┬", "light down-horizontal", ()),
        IconEntry("┴", "light up-horizontal", ()),
        IconEntry("┼", "light cross", ()),
        IconEntry("╭", "rounded down-right corner", ()),
        IconEntry("╮", "rounded down-left corner", ()),
        IconEntry("╯", "rounded up-left corner", ()),
        IconEntry("╰", "rounded up-right corner", ()),
        IconEntry("═", "double horizontal", ()),
        IconEntry("║", "double vertical", ()),
        IconEntry("╔", "double down-right", ()),
        IconEntry("╗", "double down-left", ()),
        IconEntry("╚", "double up-right", ()),
        IconEntry("╝", "double up-left", ()),
        IconEntry("╬", "double cross", ()),
        IconEntry("╠", "double vertical-right", ()),
        IconEntry("╣", "double vertical-left", ()),
        IconEntry("╦", "double down-horizontal", ()),
        IconEntry("╩", "double up-horizontal", ()),
        IconEntry("┄", "light triple dash horizontal", ()),
        IconEntry("┅", "heavy triple dash horizontal", ()),
        IconEntry("┈", "light quadruple dash horizontal", ()),
        IconEntry("┉", "heavy quadruple dash horizontal", ()),
        IconEntry("┊", "light quadruple dash vertical", ()),
        IconEntry("╱", "diagonal slash up-left to down-right", ()),
        IconEntry("╲", "diagonal slash up-right to down-left", ()),
        IconEntry("╳", "diagonal cross", ()),
    ],
    "Block Elements": [
        IconEntry("█", "full block", ()),
        IconEntry("▉", "left seven-eighths block", ()),
        IconEntry("▊", "left three-quarters block", ()),
        IconEntry("▋", "left five-eighths block", ()),
        IconEntry("▌", "left half block", ()),
        IconEntry("▍", "left three-eighths block", ()),
        IconEntry("▎", "left one-quarter block", ()),
        IconEntry("▏", "left one-eighth block", ()),
        IconEntry("▐", "right half block", ()),
        IconEntry("░", "light shade", ("25 percent",)),
        IconEntry("▒", "medium shade", ("50 percent",)),
        IconEntry("▓", "dark shade", ("75 percent",)),
        IconEntry("▀", "upper half block", ()),
        IconEntry("▁", "lower one-eighth block", ()),
        IconEntry("▂", "lower one-quarter block", ()),
        IconEntry("▃", "lower three-eighths block", ()),
        IconEntry("▄", "lower half block", ()),
        IconEntry("▅", "lower five-eighths block", ()),
        IconEntry("▆", "lower three-quarters block", ()),
        IconEntry("▇", "lower seven-eighths block", ()),
        IconEntry("▖", "quadrant lower-left", ()),
        IconEntry("▗", "quadrant lower-right", ()),
        IconEntry("▘", "quadrant upper-left", ()),
        IconEntry("▙", "quadrant upper-left and lower", ()),
        IconEntry("▚", "quadrant upper-left and lower-right", ()),
        IconEntry("▛", "quadrant upper and lower-left", ()),
        IconEntry("▜", "quadrant upper and lower-right", ()),
        IconEntry("▝", "quadrant upper-right", ()),
        IconEntry("▞", "quadrant upper-right and lower-left", ()),
        IconEntry("▟", "quadrant upper-right and lower", ()),
    ],
    "Hands & Pointing": [
        IconEntry("☚", "black left index", ()),
        IconEntry("☛", "black right index", ()),
        IconEntry("☜", "white left index", ()),
        IconEntry("☝", "white up index", ()),
        IconEntry("☞", "white right index", ("note",)),
        IconEntry("☟", "white down index", ()),
        IconEntry("👆", "backhand index up", ()),
        IconEntry("👇", "backhand index down", ()),
        IconEntry("👈", "backhand index left", ()),
        IconEntry("👉", "backhand index right", ("look",)),
        IconEntry("👍", "thumbs up", ("approve",)),
        IconEntry("👎", "thumbs down", ("reject",)),
        IconEntry("✊", "raised fist", ()),
        IconEntry("✋", "raised hand", ("stop",)),
        IconEntry("✌", "victory", ("two",)),
        IconEntry("🤝", "handshake", ("deal", "merger")),
        IconEntry("🤞", "fingers crossed", ("luck",)),
        IconEntry("🙏", "folded hands", ("thanks",)),
        IconEntry("✍", "writing hand", ("sign",)),
        IconEntry("👋", "waving hand", ("hello",)),
        IconEntry("👏", "clapping hands", ("applause",)),
    ],
    "Weather & Climate": [
        IconEntry("☀", "sun", ("clear",)),
        IconEntry("☁", "cloud", ("overcast",)),
        IconEntry("⛅", "sun behind cloud", ("partly cloudy",)),
        IconEntry("⛈", "cloud with thunder", ("storm",)),
        IconEntry("🌤", "sun small cloud", ()),
        IconEntry("🌥", "sun large cloud", ()),
        IconEntry("🌦", "sun behind rain cloud", ()),
        IconEntry("🌧", "rain cloud", ("rain",)),
        IconEntry("🌨", "snow cloud", ("snow",)),
        IconEntry("🌩", "lightning cloud", ("thunder",)),
        IconEntry("🌪", "tornado", ("volatility", "crash")),
        IconEntry("🌫", "fog", ("uncertainty",)),
        IconEntry("🌬", "wind face", ()),
        IconEntry("☂", "umbrella", ("hedge",)),
        IconEntry("☔", "umbrella with rain", ("protection",)),
        IconEntry("☃", "snowman", ()),
        IconEntry("⛄", "snowman without snow", ()),
        IconEntry("❄", "snowflake", ()),
        IconEntry("🌡", "thermometer", ("temperature",)),
        IconEntry("🌊", "wave", ("liquidity",)),
        IconEntry("🔥", "fire", ("hot", "trending")),
        IconEntry("💧", "droplet", ()),
        IconEntry("☔", "umbrella rain", ()),
    ],
    "Vehicles & Transport": [
        IconEntry("🚗", "car", ("autos",)),
        IconEntry("🚕", "taxi", ()),
        IconEntry("🚙", "SUV", ()),
        IconEntry("🚐", "minibus", ()),
        IconEntry("🚚", "delivery truck", ("logistics",)),
        IconEntry("🚛", "articulated lorry", ("freight",)),
        IconEntry("🚜", "tractor", ("agriculture",)),
        IconEntry("🏎", "racing car", ("speed",)),
        IconEntry("🏍", "motorcycle", ()),
        IconEntry("🛵", "scooter", ()),
        IconEntry("🚲", "bicycle", ()),
        IconEntry("🛴", "kick scooter", ()),
        IconEntry("🚌", "bus", ()),
        IconEntry("🚎", "trolleybus", ()),
        IconEntry("🚓", "police car", ()),
        IconEntry("🚑", "ambulance", ()),
        IconEntry("🚒", "fire engine", ()),
        IconEntry("🚀", "rocket", ("growth", "launch")),
        IconEntry("🛸", "ufo", ()),
        IconEntry("🛰", "satellite", ("data feed",)),
        IconEntry("🛩", "small plane", ()),
        IconEntry("✈", "airplane", ()),
        IconEntry("🚁", "helicopter", ()),
        IconEntry("⛵", "sailboat", ()),
        IconEntry("🚤", "speedboat", ()),
        IconEntry("🛥", "motor boat", ()),
        IconEntry("🛳", "passenger ship", ()),
        IconEntry("⛴", "ferry", ()),
        IconEntry("🚢", "ship", ()),
        IconEntry("🚂", "locomotive", ()),
        IconEntry("🚆", "train", ()),
        IconEntry("🚇", "metro", ()),
        IconEntry("🚉", "station", ()),
    ],
    "Buildings & Places": [
        IconEntry("🗺", "world map", ()),
        IconEntry("🏔", "snow-capped mountain", ()),
        IconEntry("⛰", "mountain", ()),
        IconEntry("🌋", "volcano", ("crash", "shock")),
        IconEntry("🗻", "Mount Fuji", ()),
        IconEntry("🏕", "camping", ()),
        IconEntry("🏖", "beach with umbrella", ("vacation",)),
        IconEntry("🏜", "desert", ("dry", "drought")),
        IconEntry("🏝", "desert island", ()),
        IconEntry("🏞", "national park", ()),
        IconEntry("🏟", "stadium", ()),
        IconEntry("🏛", "classical building", ("government",)),
        IconEntry("🏗", "construction", ("building",)),
        IconEntry("🏘", "houses", ("real estate",)),
        IconEntry("🏚", "derelict house", ()),
        IconEntry("🏠", "house", ()),
        IconEntry("🏡", "house with garden", ()),
        IconEntry("🏢", "office building", ("corporate",)),
        IconEntry("🏣", "japanese post office", ()),
        IconEntry("🏤", "european post office", ()),
        IconEntry("🏥", "hospital", ()),
        IconEntry("🏦", "bank", ()),
        IconEntry("🏧", "ATM", ()),
        IconEntry("🏨", "hotel", ()),
        IconEntry("🏪", "convenience store", ("retail",)),
        IconEntry("🏫", "school", ()),
        IconEntry("🏬", "department store", ()),
        IconEntry("🏭", "factory", ("industrials",)),
        IconEntry("🏯", "japanese castle", ()),
        IconEntry("🏰", "european castle", ()),
        IconEntry("💒", "wedding chapel", ()),
        IconEntry("🗼", "Tokyo tower", ()),
        IconEntry("🗽", "Statue of Liberty", ()),
        IconEntry("⛪", "church", ()),
        IconEntry("🕌", "mosque", ()),
        IconEntry("🕍", "synagogue", ()),
        IconEntry("⛩", "shinto shrine", ()),
        IconEntry("🛕", "hindu temple", ()),
        IconEntry("🕋", "kaaba", ()),
    ],
    "Time & Clocks": [
        IconEntry("⌚", "watch", ()),
        IconEntry("⌛", "hourglass full", ()),
        IconEntry("⏳", "hourglass flowing", ()),
        IconEntry("⏰", "alarm clock", ()),
        IconEntry("⏱", "stopwatch", ()),
        IconEntry("⏲", "timer clock", ()),
        IconEntry("🕰", "mantelpiece clock", ()),
        IconEntry("🕐", "1 o'clock", ()),
        IconEntry("🕑", "2 o'clock", ()),
        IconEntry("🕒", "3 o'clock", ()),
        IconEntry("🕓", "4 o'clock", ()),
        IconEntry("🕔", "5 o'clock", ()),
        IconEntry("🕕", "6 o'clock", ()),
        IconEntry("🕖", "7 o'clock", ()),
        IconEntry("🕗", "8 o'clock", ()),
        IconEntry("🕘", "9 o'clock", ()),
        IconEntry("🕙", "10 o'clock", ()),
        IconEntry("🕚", "11 o'clock", ()),
        IconEntry("🕛", "12 o'clock", ()),
    ],
    "Punctuation & Typography": [
        IconEntry("…", "ellipsis", ("more",)),
        IconEntry("·", "middle dot", ("separator",)),
        IconEntry("•", "bullet", ()),
        IconEntry("‣", "triangular bullet", ()),
        IconEntry("⁃", "hyphen bullet", ()),
        IconEntry("⁌", "black leftwards bullet", ()),
        IconEntry("⁍", "black rightwards bullet", ()),
        IconEntry("‒", "figure dash", ()),
        IconEntry("–", "en dash", ()),
        IconEntry("—", "em dash", ()),
        IconEntry("―", "horizontal bar", ()),
        IconEntry("‖", "double vertical line", ()),
        IconEntry("‰", "per mille", ("permille",)),
        IconEntry("‱", "per ten thousand", ()),
        IconEntry("§", "section", ()),
        IconEntry("¶", "pilcrow", ("paragraph",)),
        IconEntry("†", "dagger", ("footnote",)),
        IconEntry("‡", "double dagger", ()),
        IconEntry("‼", "double exclamation", ()),
        IconEntry("⁇", "double question", ()),
        IconEntry("⁈", "question exclamation", ()),
        IconEntry("⁉", "exclamation question", ()),
        IconEntry("❝", "heavy double turned comma quotation", ()),
        IconEntry("❞", "heavy double comma quotation", ()),
        IconEntry("❛", "heavy single turned comma quotation", ()),
        IconEntry("❜", "heavy single comma quotation", ()),
        IconEntry("⁂", "asterism", ()),
        IconEntry("⁕", "flower punctuation", ()),
        IconEntry("⁘", "four dot mark", ()),
        IconEntry("⁙", "five dot punctuation", ()),
        IconEntry("⁛", "four dot punctuation", ()),
    ],
    "Brackets & Bullets": [
        IconEntry("⟨", "mathematical left angle", ()),
        IconEntry("⟩", "mathematical right angle", ()),
        IconEntry("⟪", "double angle left", ()),
        IconEntry("⟫", "double angle right", ()),
        IconEntry("⟮", "flat left bracket", ()),
        IconEntry("⟯", "flat right bracket", ()),
        IconEntry("⦃", "left curly with bar", ()),
        IconEntry("⦄", "right curly with bar", ()),
        IconEntry("⦅", "left double parenthesis", ()),
        IconEntry("⦆", "right double parenthesis", ()),
        IconEntry("⌈", "left ceiling", ()),
        IconEntry("⌉", "right ceiling", ()),
        IconEntry("⌊", "left floor", ()),
        IconEntry("⌋", "right floor", ()),
        IconEntry("『", "left white corner", ()),
        IconEntry("』", "right white corner", ()),
        IconEntry("「", "left corner", ()),
        IconEntry("」", "right corner", ()),
        IconEntry("【", "left black lenticular", ()),
        IconEntry("】", "right black lenticular", ()),
        IconEntry("〔", "left tortoise shell", ()),
        IconEntry("〕", "right tortoise shell", ()),
    ],
    "Devices & Tools": [
        IconEntry("🖥", "desktop computer", ()),
        IconEntry("💻", "laptop", ()),
        IconEntry("⌨", "keyboard", ()),
        IconEntry("🖱", "mouse", ()),
        IconEntry("🖲", "trackball", ()),
        IconEntry("💽", "minidisc", ()),
        IconEntry("💾", "floppy disk", ("save",)),
        IconEntry("💿", "optical disc", ()),
        IconEntry("📀", "DVD", ()),
        IconEntry("🎙", "studio microphone", ()),
        IconEntry("🎚", "level slider", ()),
        IconEntry("🎛", "control knobs", ()),
        IconEntry("🎞", "film frames", ()),
        IconEntry("📺", "television", ()),
        IconEntry("📻", "radio", ()),
        IconEntry("📷", "camera", ()),
        IconEntry("📸", "camera with flash", ()),
        IconEntry("📹", "video camera", ()),
        IconEntry("📼", "videocassette", ()),
        IconEntry("🔌", "plug", ("power",)),
        IconEntry("🔋", "battery", ("energy",)),
        IconEntry("📡", "satellite antenna", ()),
        IconEntry("⚙", "gear", ("settings",)),
        IconEntry("🛠", "hammer and wrench", ("config",)),
        IconEntry("🔧", "wrench", ()),
        IconEntry("🔨", "hammer", ()),
        IconEntry("🔩", "nut and bolt", ()),
        IconEntry("⛏", "pick", ()),
        IconEntry("🪓", "axe", ()),
        IconEntry("🔬", "microscope", ()),
        IconEntry("🔭", "telescope", ()),
        IconEntry("⚗", "alembic", ("research",)),
    ],
    "Signs & Roman Numerals": [
        IconEntry("Ⅰ", "roman 1", ()),
        IconEntry("Ⅱ", "roman 2", ()),
        IconEntry("Ⅲ", "roman 3", ()),
        IconEntry("Ⅳ", "roman 4", ()),
        IconEntry("Ⅴ", "roman 5", ()),
        IconEntry("Ⅵ", "roman 6", ()),
        IconEntry("Ⅶ", "roman 7", ()),
        IconEntry("Ⅷ", "roman 8", ()),
        IconEntry("Ⅸ", "roman 9", ()),
        IconEntry("Ⅹ", "roman 10", ()),
        IconEntry("Ⅺ", "roman 11", ()),
        IconEntry("Ⅻ", "roman 12", ()),
        IconEntry("Ⅼ", "roman 50", ()),
        IconEntry("Ⅽ", "roman 100", ()),
        IconEntry("Ⅾ", "roman 500", ()),
        IconEntry("Ⅿ", "roman 1000", ()),
        IconEntry("①", "circled 1", ()),
        IconEntry("②", "circled 2", ()),
        IconEntry("③", "circled 3", ()),
        IconEntry("④", "circled 4", ()),
        IconEntry("⑤", "circled 5", ()),
        IconEntry("⑥", "circled 6", ()),
        IconEntry("⑦", "circled 7", ()),
        IconEntry("⑧", "circled 8", ()),
        IconEntry("⑨", "circled 9", ()),
        IconEntry("⑩", "circled 10", ()),
        IconEntry("⒜", "parenthesised a", ()),
        IconEntry("⒝", "parenthesised b", ()),
        IconEntry("⒞", "parenthesised c", ()),
        IconEntry("ⓐ", "circled a", ()),
        IconEntry("ⓑ", "circled b", ()),
        IconEntry("ⓒ", "circled c", ()),
    ],
}


def all_icons() -> List[IconEntry]:
    """Flatten the gallery into one list (preserves category order)."""
    out: List[IconEntry] = []
    for entries in ICON_GALLERY.values():
        out.extend(entries)
    return out


def search_icons(query: str) -> List[IconEntry]:
    """Case-insensitive substring search across name + keywords + glyph."""
    q = (query or "").strip().lower()
    if not q:
        return all_icons()
    hits: List[IconEntry] = []
    for entry in all_icons():
        haystack = " ".join((entry.name, entry.glyph, *entry.keywords)).lower()
        if q in haystack:
            hits.append(entry)
    return hits


# ---------------------------------------------------------------------------
# Colour palettes
# ---------------------------------------------------------------------------

@dataclass
class ColorSwatch:
    name: str
    hex: str


# Curated palettes — every one of these is also useful for theming the
# real Suite. Hex codes lower-case, no shorthand.
COLOR_PALETTES: Dict[str, List[ColorSwatch]] = {
    "Catppuccin Mocha": [
        ColorSwatch("Rosewater", "#f5e0dc"),
        ColorSwatch("Flamingo",  "#f2cdcd"),
        ColorSwatch("Pink",      "#f5c2e7"),
        ColorSwatch("Mauve",     "#cba6f7"),
        ColorSwatch("Red",       "#f38ba8"),
        ColorSwatch("Maroon",    "#eba0ac"),
        ColorSwatch("Peach",     "#fab387"),
        ColorSwatch("Yellow",    "#f9e2af"),
        ColorSwatch("Green",     "#a6e3a1"),
        ColorSwatch("Teal",      "#94e2d5"),
        ColorSwatch("Sky",       "#89dceb"),
        ColorSwatch("Sapphire",  "#74c7ec"),
        ColorSwatch("Blue",      "#89b4fa"),
        ColorSwatch("Lavender",  "#b4befe"),
        ColorSwatch("Text",      "#cdd6f4"),
        ColorSwatch("Subtext1",  "#bac2de"),
        ColorSwatch("Subtext0",  "#a6adc8"),
        ColorSwatch("Overlay2",  "#9399b2"),
        ColorSwatch("Overlay1",  "#7f849c"),
        ColorSwatch("Overlay0",  "#6c7086"),
        ColorSwatch("Surface2",  "#585b70"),
        ColorSwatch("Surface1",  "#45475a"),
        ColorSwatch("Surface0",  "#313244"),
        ColorSwatch("Base",      "#1e1e2e"),
        ColorSwatch("Mantle",    "#181825"),
        ColorSwatch("Crust",     "#11111b"),
    ],
    "Catppuccin Latte": [
        ColorSwatch("Rosewater", "#dc8a78"),
        ColorSwatch("Flamingo",  "#dd7878"),
        ColorSwatch("Pink",      "#ea76cb"),
        ColorSwatch("Mauve",     "#8839ef"),
        ColorSwatch("Red",       "#d20f39"),
        ColorSwatch("Maroon",    "#e64553"),
        ColorSwatch("Peach",     "#fe640b"),
        ColorSwatch("Yellow",    "#df8e1d"),
        ColorSwatch("Green",     "#40a02b"),
        ColorSwatch("Teal",      "#179299"),
        ColorSwatch("Sky",       "#04a5e5"),
        ColorSwatch("Sapphire",  "#209fb5"),
        ColorSwatch("Blue",      "#1e66f5"),
        ColorSwatch("Lavender",  "#7287fd"),
        ColorSwatch("Text",      "#4c4f69"),
        ColorSwatch("Subtext1",  "#5c5f77"),
        ColorSwatch("Subtext0",  "#6c6f85"),
        ColorSwatch("Overlay2",  "#7c7f93"),
        ColorSwatch("Overlay1",  "#8c8fa1"),
        ColorSwatch("Overlay0",  "#9ca0b0"),
        ColorSwatch("Surface2",  "#acb0be"),
        ColorSwatch("Surface1",  "#bcc0cc"),
        ColorSwatch("Surface0",  "#ccd0da"),
        ColorSwatch("Base",      "#eff1f5"),
        ColorSwatch("Mantle",    "#e6e9ef"),
        ColorSwatch("Crust",     "#dce0e8"),
    ],
    "Material Design": [
        ColorSwatch("Red 500",       "#f44336"),
        ColorSwatch("Pink 500",      "#e91e63"),
        ColorSwatch("Purple 500",    "#9c27b0"),
        ColorSwatch("Deep Purple",   "#673ab7"),
        ColorSwatch("Indigo 500",    "#3f51b5"),
        ColorSwatch("Blue 500",      "#2196f3"),
        ColorSwatch("Light Blue",    "#03a9f4"),
        ColorSwatch("Cyan 500",      "#00bcd4"),
        ColorSwatch("Teal 500",      "#009688"),
        ColorSwatch("Green 500",     "#4caf50"),
        ColorSwatch("Light Green",   "#8bc34a"),
        ColorSwatch("Lime 500",      "#cddc39"),
        ColorSwatch("Yellow 500",    "#ffeb3b"),
        ColorSwatch("Amber 500",     "#ffc107"),
        ColorSwatch("Orange 500",    "#ff9800"),
        ColorSwatch("Deep Orange",   "#ff5722"),
        ColorSwatch("Brown 500",     "#795548"),
        ColorSwatch("Grey 500",      "#9e9e9e"),
        ColorSwatch("Blue Grey",     "#607d8b"),
        ColorSwatch("Black",         "#000000"),
        ColorSwatch("White",         "#ffffff"),
    ],
    "Tailwind CSS": [
        ColorSwatch("slate-500",   "#64748b"),
        ColorSwatch("gray-500",    "#6b7280"),
        ColorSwatch("zinc-500",    "#71717a"),
        ColorSwatch("red-500",     "#ef4444"),
        ColorSwatch("orange-500",  "#f97316"),
        ColorSwatch("amber-500",   "#f59e0b"),
        ColorSwatch("yellow-500",  "#eab308"),
        ColorSwatch("lime-500",    "#84cc16"),
        ColorSwatch("green-500",   "#22c55e"),
        ColorSwatch("emerald-500", "#10b981"),
        ColorSwatch("teal-500",    "#14b8a6"),
        ColorSwatch("cyan-500",    "#06b6d4"),
        ColorSwatch("sky-500",     "#0ea5e9"),
        ColorSwatch("blue-500",    "#3b82f6"),
        ColorSwatch("indigo-500",  "#6366f1"),
        ColorSwatch("violet-500",  "#8b5cf6"),
        ColorSwatch("purple-500",  "#a855f7"),
        ColorSwatch("fuchsia-500", "#d946ef"),
        ColorSwatch("pink-500",    "#ec4899"),
        ColorSwatch("rose-500",    "#f43f5e"),
    ],
    "Solarized": [
        ColorSwatch("base03",  "#002b36"),
        ColorSwatch("base02",  "#073642"),
        ColorSwatch("base01",  "#586e75"),
        ColorSwatch("base00",  "#657b83"),
        ColorSwatch("base0",   "#839496"),
        ColorSwatch("base1",   "#93a1a1"),
        ColorSwatch("base2",   "#eee8d5"),
        ColorSwatch("base3",   "#fdf6e3"),
        ColorSwatch("yellow",  "#b58900"),
        ColorSwatch("orange",  "#cb4b16"),
        ColorSwatch("red",     "#dc322f"),
        ColorSwatch("magenta", "#d33682"),
        ColorSwatch("violet",  "#6c71c4"),
        ColorSwatch("blue",    "#268bd2"),
        ColorSwatch("cyan",    "#2aa198"),
        ColorSwatch("green",   "#859900"),
    ],
    "Dracula": [
        ColorSwatch("Background", "#282a36"),
        ColorSwatch("Current Line","#44475a"),
        ColorSwatch("Foreground", "#f8f8f2"),
        ColorSwatch("Comment",    "#6272a4"),
        ColorSwatch("Cyan",       "#8be9fd"),
        ColorSwatch("Green",      "#50fa7b"),
        ColorSwatch("Orange",     "#ffb86c"),
        ColorSwatch("Pink",       "#ff79c6"),
        ColorSwatch("Purple",     "#bd93f9"),
        ColorSwatch("Red",        "#ff5555"),
        ColorSwatch("Yellow",     "#f1fa8c"),
    ],
    "Nord": [
        ColorSwatch("Polar 0",  "#2e3440"),
        ColorSwatch("Polar 1",  "#3b4252"),
        ColorSwatch("Polar 2",  "#434c5e"),
        ColorSwatch("Polar 3",  "#4c566a"),
        ColorSwatch("Snow 0",   "#d8dee9"),
        ColorSwatch("Snow 1",   "#e5e9f0"),
        ColorSwatch("Snow 2",   "#eceff4"),
        ColorSwatch("Frost 0",  "#8fbcbb"),
        ColorSwatch("Frost 1",  "#88c0d0"),
        ColorSwatch("Frost 2",  "#81a1c1"),
        ColorSwatch("Frost 3",  "#5e81ac"),
        ColorSwatch("Aurora R", "#bf616a"),
        ColorSwatch("Aurora O", "#d08770"),
        ColorSwatch("Aurora Y", "#ebcb8b"),
        ColorSwatch("Aurora G", "#a3be8c"),
        ColorSwatch("Aurora P", "#b48ead"),
    ],
    "Gruvbox Dark": [
        ColorSwatch("bg",       "#282828"),
        ColorSwatch("bg1",      "#3c3836"),
        ColorSwatch("bg2",      "#504945"),
        ColorSwatch("bg3",      "#665c54"),
        ColorSwatch("fg",       "#ebdbb2"),
        ColorSwatch("fg1",      "#d5c4a1"),
        ColorSwatch("red",      "#cc241d"),
        ColorSwatch("green",    "#98971a"),
        ColorSwatch("yellow",   "#d79921"),
        ColorSwatch("blue",     "#458588"),
        ColorSwatch("purple",   "#b16286"),
        ColorSwatch("aqua",     "#689d6a"),
        ColorSwatch("orange",   "#d65d0e"),
        ColorSwatch("gray",     "#928374"),
    ],
    "Suite Accents": [
        ColorSwatch("Mocha bg",   "#1e1e2e"),
        ColorSwatch("Mocha card", "#2a2a3d"),
        ColorSwatch("Lynx blue",  "#89b4fa"),
        ColorSwatch("Lynx cyan",  "#74c7ec"),
        ColorSwatch("Lynx mauve", "#cba6f7"),
        ColorSwatch("Lynx green", "#a6e3a1"),
        ColorSwatch("Lynx yellow","#f9e2af"),
        ColorSwatch("Lynx red",   "#f38ba8"),
        ColorSwatch("Lynx peach", "#fab387"),
        ColorSwatch("Lynx text",  "#cdd6f4"),
        ColorSwatch("Lynx muted", "#6c7086"),
        ColorSwatch("Lynx border","#45475a"),
    ],
}


def all_palettes() -> List[str]:
    return list(COLOR_PALETTES.keys())


def palette(name: str) -> List[ColorSwatch]:
    return list(COLOR_PALETTES.get(name, ()))


# ---------------------------------------------------------------------------
# Font sample helpers
# ---------------------------------------------------------------------------

# A short sentence + numerals that exercises ascenders, descenders, and
# digits — useful for comparing fonts at a glance.
FONT_SAMPLE_SENTENCE = (
    "Lince Investor Suite — Vanguard 500 Index $1.42T  |  "
    "AaBbCc 0123456789  ▲▼ ✓ ✘ €¥£"
)


PREFERRED_FONT_FAMILIES: Tuple[str, ...] = (
    "Noto Sans",
    "Noto Sans Mono",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "Liberation Sans",
    "Liberation Mono",
    "Liberation Serif",
    "Helvetica",
    "Arial",
    "Segoe UI",
    "Consolas",
    "Courier New",
    "Menlo",
    "Monaco",
    "Times New Roman",
    "Georgia",
    "Fira Code",
    "Fira Sans",
    "JetBrains Mono",
    "Source Sans 3",
    "Source Code Pro",
    "Roboto",
    "Roboto Mono",
    "Cantarell",
    "Ubuntu",
    "Ubuntu Mono",
    "Inter",
    "Lato",
    "Open Sans",
)


def order_fonts(available: List[str]) -> List[str]:
    """Return *available* with PREFERRED families surfaced first."""
    avail = list(available)
    head = [f for f in PREFERRED_FONT_FAMILIES if f in avail]
    seen = set(head)
    tail = [f for f in avail if f not in seen]
    return head + tail
